# Generated by Django 4.2.15 on 2024-09-02 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30, unique=True)),
                ("description", models.TextField()),
                ("slug", models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30, unique=True)),
                ("description", models.TextField()),
                ("slug", models.SlugField()),
                (
                    "region_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oka_basin.region",
                        verbose_name="region_name",
                    ),
                ),
            ],
        ),
    ]
