# Generated by Django 4.2.15 on 2024-09-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oka_basin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
