# Generated by Django 4.2.15 on 2024-09-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oka_basin", "0002_alter_region_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="slug",
            field=models.SlugField(verbose_name="Name in English"),
        ),
    ]
