# Generated by Django 4.2.15 on 2024-09-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oka_basin", "0003_alter_region_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
