# Generated by Django 4.2.15 on 2024-09-03 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("oka_basin", "0004_alter_region_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="district",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="district",
            name="slug",
            field=models.SlugField(verbose_name="Name in English"),
        ),
        migrations.CreateModel(
            name="SpecDistr",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("val", models.IntegerField(blank=True, null=True)),
                (
                    "district_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oka_basin.district",
                        verbose_name="district_name",
                    ),
                ),
            ],
        ),
    ]
