# Generated by Django 4.2.15 on 2024-09-05 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oka_basin", "0006_speciesdistrict_delete_specdistr"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SpeciesDistrict",
        ),
    ]
