# Generated by Django 4.2.15 on 2024-09-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oka_basin", "0007_delete_speciesdistrict"),
    ]

    operations = [
        migrations.RenameField(
            model_name="district",
            old_name="slug",
            new_name="name_en",
        ),
        migrations.RenameField(
            model_name="region",
            old_name="slug",
            new_name="name_en",
        ),
        migrations.AlterField(
            model_name="district",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="region",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
