# Generated by Django 4.2.15 on 2024-09-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oka_basin", "0008_rename_slug_district_name_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="district",
            name="name_en",
            field=models.SlugField(blank=True, verbose_name="Name in English"),
        ),
        migrations.AlterField(
            model_name="region",
            name="name_en",
            field=models.SlugField(blank=True, verbose_name="Name in English"),
        ),
    ]
