# Generated by Django 4.2.15 on 2024-09-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oka_basin", "0009_alter_district_name_en_alter_region_name_en"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="region",
            name="id",
            field=models.IntegerField(
                primary_key=True, serialize=False, verbose_name="Номер региона"
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="name",
            field=models.CharField(
                max_length=30, unique=True, verbose_name="Название региона"
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="name_en",
            field=models.SlugField(blank=True, verbose_name="Название на английском"),
        ),
    ]
