# Generated by Django 4.2.15 on 2024-11-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oka_basin", "0011_region_svg_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="district",
            name="svg_path",
            field=models.TextField(
                blank=True, default="", verbose_name="Границы района, SVG path"
            ),
        ),
    ]
