# Generated by Django 4.2.15 on 2024-09-06 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("oka_basin", "0007_delete_speciesdistrict"),
        ("flora", "0002_speciesdistrict_district_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="speciesdistrict",
            name="dist1",
        ),
        migrations.RemoveField(
            model_name="speciesdistrict",
            name="dist2",
        ),
        migrations.AddField(
            model_name="species",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="species",
            name="name_ru",
            field=models.CharField(default="Уточнить", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="index",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="index Majevsky"
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="name_full",
            field=models.CharField(default="Уточнить", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="speciesdistrict",
            name="district_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="oka_basin.district",
                verbose_name="district name",
            ),
        ),
    ]
