# Generated by Django 4.2.15 on 2024-09-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flora", "0003_remove_speciesdistrict_dist1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="species",
            name="name_full",
            field=models.CharField(default="Уточнить", max_length=50),
        ),
        migrations.AlterField(
            model_name="species",
            name="name_ru",
            field=models.CharField(default="Уточнить", max_length=50),
        ),
    ]
