# Generated by Django 4.2.15 on 2024-09-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flora", "0006_remove_species_name_ru"),
    ]

    operations = [
        migrations.AddField(
            model_name="species",
            name="name_ru",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
