# Generated by Django 4.2.15 on 2024-09-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flora", "0007_species_name_ru"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speciesdistrict",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Not found"), (2, "Not documented")], default=0
            ),
        ),
    ]
