# Generated by Django 4.2.15 on 2024-09-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flora", "0008_alter_speciesdistrict_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speciesdistrict",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Not found"),
                    (2, "Not documented"),
                    (3, "Old record"),
                    (4, "Old Herbarium"),
                    (5, "New Herbarium"),
                ],
                default=0,
            ),
        ),
    ]
