# Generated by Django 4.2.15 on 2024-09-08 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flora", "0009_alter_speciesdistrict_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "index",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="index Majevsky"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Name one word"
                    ),
                ),
                ("name_full", models.CharField(blank=True, max_length=50, null=True)),
                ("name_ru", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("distribution", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="speciesdistrict",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Not found"),
                    (1, "Not documented"),
                    (2, "Old record"),
                    (3, "Old Herbarium"),
                    (4, "New Herbarium"),
                ],
                default=0,
            ),
        ),
        migrations.CreateModel(
            name="Genus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "index",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="index Majevsky"
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                ("name_full", models.CharField(blank=True, max_length=50, null=True)),
                ("name_ru", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("distribution", models.TextField(blank=True, null=True)),
                (
                    "family",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flora.family",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="species",
            name="genus",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="flora.family",
            ),
        ),
    ]
