# Generated by Django 4.2.15 on 2024-09-08 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flora", "0010_family_alter_speciesdistrict_status_genus_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genus",
            name="family",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="flora.family"
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="genus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="flora.family"
            ),
        ),
    ]
