# Generated by Django 4.2.15 on 2024-09-08 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flora", "0011_alter_genus_family_alter_species_genus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="species",
            name="genus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="flora.genus"
            ),
        ),
    ]
