# Generated by Django 4.2.15 on 2024-09-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flora", "0014_locations_reliability_alter_family_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locations",
            name="coordinate_lat_n",
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
        migrations.AlterField(
            model_name="locations",
            name="coordinate_long_e",
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
    ]
