# Generated by Django 4.2.15 on 2024-09-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flora", "0016_rename_locations_location_alter_family_name_full"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="source_person",
            new_name="source_info",
        ),
        migrations.RemoveField(
            model_name="location",
            name="source_acronym",
        ),
        migrations.RemoveField(
            model_name="location",
            name="source_inaturalist",
        ),
        migrations.RemoveField(
            model_name="location",
            name="source_publication",
        ),
        migrations.AddField(
            model_name="location",
            name="source_type",
            field=models.IntegerField(
                choices=[
                    (1, "Гербарий, окроним"),
                    (2, "Публикация, данные публикации"),
                    (3, "INaturalist, ссылка"),
                    (4, "Наблюдение, карточки, ФИО автора, "),
                ],
                default=1,
            ),
        ),
    ]
