# Generated by Django 4.2.15 on 2024-09-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flora", "0018_rename_name_ru_synonyms_species_name_syn_lat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="species",
            name="work_status",
            field=models.IntegerField(
                choices=[(0, "черновик"), (1, "в работе"), (2, "завершен")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="source_type",
            field=models.IntegerField(
                choices=[
                    (0, "Гербарий, окроним"),
                    (1, "Публикация, данные публикации"),
                    (2, "INaturalist, ссылка"),
                    (3, "Наблюдение, карточки, ФИО автора, "),
                ],
                default=0,
            ),
        ),
    ]
